### ISSUE TITLE
Customize python versions

### ISSUE THREAD

**Issue by dmerejkowsky** [dmerejkowsky/dmenv#1]
Maybe a config file like this:

```toml
[env."3.7"]
python = "/path/to/python-3.7"

```

And then a `.venv/3.7` folder will be used
